// flow-typed signature: 053bc2c27ddf31c02a4202aa4122775d
// flow-typed version: <<STUB>>/in-array_v^0.1.2/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'in-array'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'in-array' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'in-array/index' {
  declare module.exports: $Exports<'in-array'>;
}
declare module 'in-array/index.js' {
  declare module.exports: $Exports<'in-array'>;
}
